version: '3.7'

services:
  main:
    container_name: main
    environment:
      - NATS_URL=nats://nats:4222
      - REDIS_URL=redis://redis:6379
    build:
      context: .
      target: production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: npm run start:prod
    networks:
      - webnet

networks:
  webnet:
