version: '3.7'

services:
  main:
    container_name: main
    environment:
      - NATS_URL=nats://nats:4222
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: npm run start:dev
    networks:
      - webnet
    depends_on:
      - redis
      - nats

  redis:
    container_name: redis
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    networks:
      - webnet

  nats:
    container_name: nats
    image: 'bitnami/nats:latest'
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    networks:
      - webnet

networks:
  webnet:
